version: '3'

services:
  mongo:
    image: mongo:5.0.13
    container_name: mongo_database
    restart: always
    ports: 
      - '27017:27017'
    environment: 
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
        MONGO_INITDB_DATABASE: buenavida
    volumes:
      - ./_mongo:/data/db

  pg: 
    image: postgres:alpine3.16
    container_name: pg_database
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: buenavida
    volumes: 
      - ./_postgres:/var/lib/postgresql/data
      # Copy files into the container to initialize the
      # first time
      - ./database:/files 
  
  api:
    build: .
    restart: on-failure
    ports: 
      - '3030:3030'
    links: 
      - mongo
      - pg
    container_name: golang_api
    depends_on:
      - mongo
      - pg
    volumes:
      - ./api/:/usr/src/buenavida/api
    command: air
