version: '3'

services:
  mongo:
    image: mongo:5.0.13
    container_name: buenavidaDatabase
    restart: always
    ports: 
      - '27017:27017'
    environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: superpassword2022
    volumes:
      - ./database:/data/db
  api:
    build: .
    restart: on-failure
    ports: 
      - '3030:3030'
    container_name: buenavidaAPI
    depends_on:
      - mongo
    volumes:
      - ./api/:/usr/src/buenavida/api
    command: air
